// <auto-generated />
using System;
using BusTicketing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusTicketing.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901141805_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusTicketing.Domain.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("AutoGenerationPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_generation_paused");

                    b.Property<string>("BookingReferencePrefix")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("booking_reference_prefix");

                    b.Property<int>("CounterReservationExpiryHours")
                        .HasColumnType("integer")
                        .HasColumnName("counter_reservation_expiry_hours");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<int>("GenerationWindowDays")
                        .HasColumnType("integer")
                        .HasColumnName("generation_window_days");

                    b.Property<string>("IntervalOptionsCsv")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("interval_options_csv");

                    b.Property<int>("PendingOnlinePaymentExpiryHours")
                        .HasColumnType("integer")
                        .HasColumnName("pending_online_payment_expiry_hours");

                    b.Property<int>("SeatHoldMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("seat_hold_minutes");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("site_name");

                    b.Property<string>("SupportPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("support_phone");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_settings");

                    b.ToTable("app_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_settings_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("BusTicketing.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("action");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor_name");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<string>("EntityId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BoardingCounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("boarding_counter_id");

                    b.Property<Guid?>("BookedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("booked_by_staff_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_staff_id");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DroppingCounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("dropping_counter_id");

                    b.Property<DateTimeOffset?>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_expires_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("PassengerEmail")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("passenger_email");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("passenger_name");

                    b.Property<string>("PassengerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("passenger_phone");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_mode");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("payment_status");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("reference");

                    b.Property<decimal?>("RefundAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("refund_amount");

                    b.Property<int>("SeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("seat_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<decimal>("UnitFare")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_fare");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("BoardingCounterId")
                        .HasDatabaseName("ix_bookings_boarding_counter_id");

                    b.HasIndex("BookedByStaffId")
                        .HasDatabaseName("ix_bookings_booked_by_staff_id");

                    b.HasIndex("DroppingCounterId")
                        .HasDatabaseName("ix_bookings_dropping_counter_id");

                    b.HasIndex("PassengerPhone")
                        .HasDatabaseName("ix_bookings_passenger_phone");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_reference");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_bookings_trip_id");

                    b.HasIndex("Status", "HoldExpiresAt")
                        .HasDatabaseName("ix_bookings_status_hold_expires_at");

                    b.HasIndex("Status", "PaymentStatus")
                        .HasDatabaseName("ix_bookings_status_payment_status");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.Bus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Amenities")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("amenities");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("class");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("operator");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("registration_number");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasColumnName("total_seats");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_buses");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_buses_is_active");

                    b.HasIndex("Operator")
                        .HasDatabaseName("ix_buses_operator");

                    b.ToTable("buses", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.BusRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ApproxDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("approx_duration_minutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_location_id");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("distance_km");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OriginLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_location_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_routes");

                    b.HasIndex("DestinationLocationId")
                        .HasDatabaseName("ix_routes_destination_location_id");

                    b.HasIndex("OriginLocationId", "DestinationLocationId", "IsActive")
                        .HasDatabaseName("ix_routes_origin_location_id_destination_location_id_is_active");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.CancellationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cancellation_policies");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ix_cancellation_policies_is_default")
                        .HasFilter("is_default");

                    b.ToTable("cancellation_policies", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.CancellationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MinHoursBeforeDeparture")
                        .HasColumnType("integer")
                        .HasColumnName("min_hours_before_departure");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<int>("RefundPercent")
                        .HasColumnType("integer")
                        .HasColumnName("refund_percent");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cancellation_rules");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_cancellation_rules_policy_id");

                    b.ToTable("cancellation_rules", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("district");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("division");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NameBn")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_bn");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_location_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_locations_name");

                    b.HasIndex("ParentLocationId")
                        .HasDatabaseName("ix_locations_parent_location_id");

                    b.HasIndex("Division", "District")
                        .HasDatabaseName("ix_locations_division_district");

                    b.HasIndex("Type", "IsActive")
                        .HasDatabaseName("ix_locations_type_is_active");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("Provider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_staff_id");

                    b.Property<string>("SenderMsisdn")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sender_msisdn");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_booking_id");

                    b.HasIndex("ReviewedByStaffId")
                        .HasDatabaseName("ix_payments_reviewed_by_staff_id");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_payments_transaction_id");

                    b.HasIndex("Mode", "Status")
                        .HasDatabaseName("ix_payments_mode_status");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.ScheduleTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BoardingCounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("boarding_counter_id");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uuid")
                        .HasColumnName("bus_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DroppingCounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("dropping_counter_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal>("Fare")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fare");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("OperatingDays")
                        .HasMaxLength(32)
                        .HasColumnType("integer")
                        .HasColumnName("operating_days");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_schedule_templates");

                    b.HasIndex("BoardingCounterId")
                        .HasDatabaseName("ix_schedule_templates_boarding_counter_id");

                    b.HasIndex("BusId")
                        .HasDatabaseName("ix_schedule_templates_bus_id");

                    b.HasIndex("DroppingCounterId")
                        .HasDatabaseName("ix_schedule_templates_dropping_counter_id");

                    b.HasIndex("RouteId", "IsActive")
                        .HasDatabaseName("ix_schedule_templates_route_id_is_active");

                    b.ToTable("schedule_templates", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.StaffRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.StaffUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<Guid?>("CounterLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("counter_location_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("CounterLocationId")
                        .HasDatabaseName("ix_asp_net_users_counter_location_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ArrivalTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_time");

                    b.Property<Guid?>("BoardingCounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("boarding_counter_id");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uuid")
                        .HasColumnName("bus_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DepartureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_time");

                    b.Property<Guid?>("DroppingCounterId")
                        .HasColumnType("uuid")
                        .HasColumnName("dropping_counter_id");

                    b.Property<decimal>("Fare")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fare");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual_override");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<Guid?>("ScheduleTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_template_id");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("service_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("BoardingCounterId")
                        .HasDatabaseName("ix_trips_boarding_counter_id");

                    b.HasIndex("BusId")
                        .HasDatabaseName("ix_trips_bus_id");

                    b.HasIndex("DroppingCounterId")
                        .HasDatabaseName("ix_trips_dropping_counter_id");

                    b.HasIndex("ServiceDate")
                        .HasDatabaseName("ix_trips_service_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_trips_status");

                    b.HasIndex("RouteId", "DepartureTime")
                        .HasDatabaseName("ix_trips_route_id_departure_time");

                    b.HasIndex("ScheduleTemplateId", "DepartureTime")
                        .IsUnique()
                        .HasDatabaseName("ix_trips_schedule_template_id_departure_time")
                        .HasFilter("schedule_template_id IS NOT NULL");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.TripSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("HoldExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hold_expires_at");

                    b.Property<Guid?>("HoldToken")
                        .HasColumnType("uuid")
                        .HasColumnName("hold_token");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("seat_number");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("seat_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_trip_seats");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_trip_seats_booking_id");

                    b.HasIndex("Status", "HoldExpiresAt")
                        .HasDatabaseName("ix_trip_seats_status_hold_expires_at");

                    b.HasIndex("TripId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_trip_seats_trip_id_seat_number");

                    b.ToTable("trip_seats", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("BusTicketing.Domain.Booking", b =>
                {
                    b.HasOne("BusTicketing.Domain.Location", "BoardingCounter")
                        .WithMany()
                        .HasForeignKey("BoardingCounterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bookings_locations_boarding_counter_id");

                    b.HasOne("BusTicketing.Domain.StaffUser", "BookedByStaff")
                        .WithMany()
                        .HasForeignKey("BookedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bookings_users_booked_by_staff_id");

                    b.HasOne("BusTicketing.Domain.Location", "DroppingCounter")
                        .WithMany()
                        .HasForeignKey("DroppingCounterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bookings_locations_dropping_counter_id");

                    b.HasOne("BusTicketing.Domain.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_trips_trip_id");

                    b.OwnsMany("BusTicketing.Domain.BookingSeat", "Seats", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid")
                                .HasColumnName("booking_id");

                            b1.Property<string>("SeatNumber")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("seat_number");

                            b1.HasKey("BookingId", "SeatNumber")
                                .HasName("pk_booking_seat");

                            b1.ToTable("booking_seat", (string)null);

                            b1.WithOwner("Booking")
                                .HasForeignKey("BookingId")
                                .HasConstraintName("fk_booking_seat_bookings_booking_id");

                            b1.Navigation("Booking");
                        });

                    b.Navigation("BoardingCounter");

                    b.Navigation("BookedByStaff");

                    b.Navigation("DroppingCounter");

                    b.Navigation("Seats");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BusTicketing.Domain.Bus", b =>
                {
                    b.OwnsOne("BusTicketing.Domain.SeatMap", "SeatMap", b1 =>
                        {
                            b1.Property<Guid>("BusId");

                            b1.Property<int>("Columns");

                            b1.Property<int>("Decks");

                            b1.Property<int>("Rows");

                            b1.HasKey("BusId");

                            b1.ToTable("buses");

                            b1
                                .ToJson("seat_map")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BusId")
                                .HasConstraintName("fk_buses_buses_id");

                            b1.OwnsMany("BusTicketing.Domain.SeatCell", "Seats", b2 =>
                                {
                                    b2.Property<Guid>("SeatMapBusId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<int>("Column");

                                    b2.Property<int>("Deck");

                                    b2.Property<string>("Number")
                                        .IsRequired();

                                    b2.Property<int>("Row");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(32);

                                    b2.HasKey("SeatMapBusId", "__synthesizedOrdinal")
                                        .HasName("pk_buses");

                                    b2.ToTable("buses");

                                    b2.WithOwner()
                                        .HasForeignKey("SeatMapBusId")
                                        .HasConstraintName("fk_buses_buses_seat_map_bus_id");
                                });

                            b1.Navigation("Seats");
                        });

                    b.Navigation("SeatMap")
                        .IsRequired();
                });

            modelBuilder.Entity("BusTicketing.Domain.BusRoute", b =>
                {
                    b.HasOne("BusTicketing.Domain.Location", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routes_locations_destination_location_id");

                    b.HasOne("BusTicketing.Domain.Location", "OriginLocation")
                        .WithMany()
                        .HasForeignKey("OriginLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_routes_locations_origin_location_id");

                    b.Navigation("DestinationLocation");

                    b.Navigation("OriginLocation");
                });

            modelBuilder.Entity("BusTicketing.Domain.CancellationRule", b =>
                {
                    b.HasOne("BusTicketing.Domain.CancellationPolicy", "Policy")
                        .WithMany("Rules")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cancellation_rules_cancellation_policies_policy_id");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("BusTicketing.Domain.Location", b =>
                {
                    b.HasOne("BusTicketing.Domain.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_locations_locations_parent_location_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BusTicketing.Domain.Payment", b =>
                {
                    b.HasOne("BusTicketing.Domain.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("BusTicketing.Domain.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_bookings_booking_id");

                    b.HasOne("BusTicketing.Domain.StaffUser", "ReviewedByStaff")
                        .WithMany()
                        .HasForeignKey("ReviewedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_payments_users_reviewed_by_staff_id");

                    b.Navigation("Booking");

                    b.Navigation("ReviewedByStaff");
                });

            modelBuilder.Entity("BusTicketing.Domain.ScheduleTemplate", b =>
                {
                    b.HasOne("BusTicketing.Domain.Location", "BoardingCounter")
                        .WithMany()
                        .HasForeignKey("BoardingCounterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_schedule_templates_locations_boarding_counter_id");

                    b.HasOne("BusTicketing.Domain.Bus", "Bus")
                        .WithMany("ScheduleTemplates")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_templates_buses_bus_id");

                    b.HasOne("BusTicketing.Domain.Location", "DroppingCounter")
                        .WithMany()
                        .HasForeignKey("DroppingCounterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_schedule_templates_locations_dropping_counter_id");

                    b.HasOne("BusTicketing.Domain.BusRoute", "Route")
                        .WithMany("ScheduleTemplates")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_schedule_templates_routes_route_id");

                    b.Navigation("BoardingCounter");

                    b.Navigation("Bus");

                    b.Navigation("DroppingCounter");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("BusTicketing.Domain.StaffUser", b =>
                {
                    b.HasOne("BusTicketing.Domain.Location", "CounterLocation")
                        .WithMany()
                        .HasForeignKey("CounterLocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_asp_net_users_locations_counter_location_id");

                    b.Navigation("CounterLocation");
                });

            modelBuilder.Entity("BusTicketing.Domain.Trip", b =>
                {
                    b.HasOne("BusTicketing.Domain.Location", "BoardingCounter")
                        .WithMany()
                        .HasForeignKey("BoardingCounterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trips_locations_boarding_counter_id");

                    b.HasOne("BusTicketing.Domain.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_buses_bus_id");

                    b.HasOne("BusTicketing.Domain.Location", "DroppingCounter")
                        .WithMany()
                        .HasForeignKey("DroppingCounterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trips_locations_dropping_counter_id");

                    b.HasOne("BusTicketing.Domain.BusRoute", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trips_routes_route_id");

                    b.HasOne("BusTicketing.Domain.ScheduleTemplate", "ScheduleTemplate")
                        .WithMany("Trips")
                        .HasForeignKey("ScheduleTemplateId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trips_schedule_templates_schedule_template_id");

                    b.Navigation("BoardingCounter");

                    b.Navigation("Bus");

                    b.Navigation("DroppingCounter");

                    b.Navigation("Route");

                    b.Navigation("ScheduleTemplate");
                });

            modelBuilder.Entity("BusTicketing.Domain.TripSeat", b =>
                {
                    b.HasOne("BusTicketing.Domain.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trip_seats_bookings_booking_id");

                    b.HasOne("BusTicketing.Domain.Trip", "Trip")
                        .WithMany("Seats")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_seats_trips_trip_id");

                    b.Navigation("Booking");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("BusTicketing.Domain.StaffRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BusTicketing.Domain.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BusTicketing.Domain.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("BusTicketing.Domain.StaffRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("BusTicketing.Domain.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BusTicketing.Domain.StaffUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("BusTicketing.Domain.Booking", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BusTicketing.Domain.Bus", b =>
                {
                    b.Navigation("ScheduleTemplates");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BusTicketing.Domain.BusRoute", b =>
                {
                    b.Navigation("ScheduleTemplates");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BusTicketing.Domain.CancellationPolicy", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("BusTicketing.Domain.Location", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("BusTicketing.Domain.ScheduleTemplate", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BusTicketing.Domain.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
